### PR TITLE
feat(cli): use Yargs in stead of meow

### PR DESCRIPTION
**Pull request by githrdw**
https://github.com/conventional-changelog/get-pkg-repo/issues/60

### CODE REVIEW

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
I like this update 😛 will give @hutson a chance to chime in.

**Review by hutson — APPROVED** [review]
The switch to `yargs` looks good to me.

Normally I'd ask for the formatting changes to be included in a separate follow-up PR so that each commit remains small and focused. However, this change is needed promptly by the community. So after looking over the changes, I am fine with this getting merged in as is.

**Comment by githrdw** [comment]
> Normally I'd ask for the formatting changes to be included in a separate follow-up PR so that each commit remains small and focused.

Sorry, I will do next time 👍

**Comment by githrdw** [comment]
@hutson could you merge and publish this PR?

**Comment by hutson** [comment]
> @hutson could you merge and publish this PR?

I've merged the PR, but I do not have publish access to the package on `npmjs.org`.

**Comment by drazisil** [comment]
@stevemao, besides @hutson (who does not have publish access) you are the only other person on the package. Are you able to assist in updating it to resolve the below issue?

https://github.com/conventional-changelog/standard-version/issues/772#issuecomment-895358512

**Comment by neverendingqs** [comment]
@hutson, it looks like b283d6b4833d647ab25fc7dd81c8df1a9a4c5212 added a GitHub action to automatically do a release based on conventional commit messages, but that was added after this pull request was merged.

Any chance you can add an empty commit to `master` to trigger the creation of a new version of this package?

**Pull request merged**
